name: assignment_runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  Assignment_Runner:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clone Repo
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install packages
        run: bash .github/workflows/install_dependencies.sh
      - name: Create Makefile
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_COV=true .
      - name: Build code
        run: make -j4
      - name: Run unit tests
        run: make function_tests # run all executables ending with "_test"
      - name: Run memory tests
        run: .github/workflows/memcheck.sh
